// Code generated by "stringer -type=Format"; DO NOT EDIT.

package thirteen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLEAR-0]
	_ = x[SINGLE-1]
	_ = x[PAIR-2]
	_ = x[TRIPLE-3]
	_ = x[QUAD-4]
	_ = x[THREE_RUN-5]
	_ = x[FOUR_RUN-6]
	_ = x[FIVE_RUN-7]
	_ = x[SIX_RUN-8]
	_ = x[SEVEN_RUN-9]
	_ = x[EIGHT_RUN-10]
	_ = x[NINE_RUN-11]
	_ = x[TEN_RUN-12]
	_ = x[ELEVEN_RUN-13]
	_ = x[TWELVE_RUN-14]
	_ = x[THIRTEEN_RUN-15]
	_ = x[THREE_RUN_FLUSH-16]
	_ = x[FOUR_RUN_FLUSH-17]
	_ = x[FIVE_RUN_FLUSH-18]
	_ = x[SIX_RUN_FLUSH-19]
	_ = x[SEVEN_RUN_FLUSH-20]
	_ = x[EIGHT_RUN_FLUSH-21]
	_ = x[NINE_RUN_FLUSH-22]
	_ = x[TEN_RUN_FLUSH-23]
	_ = x[ELEVEN_RUN_FLUSH-24]
	_ = x[TWELVE_RUN_FLUSH-25]
	_ = x[THIRTEEN_RUN_FLUSH-26]
}

const _Format_name = "CLEARSINGLEPAIRTRIPLEQUADTHREE_RUNFOUR_RUNFIVE_RUNSIX_RUNSEVEN_RUNEIGHT_RUNNINE_RUNTEN_RUNELEVEN_RUNTWELVE_RUNTHIRTEEN_RUNTHREE_RUN_FLUSHFOUR_RUN_FLUSHFIVE_RUN_FLUSHSIX_RUN_FLUSHSEVEN_RUN_FLUSHEIGHT_RUN_FLUSHNINE_RUN_FLUSHTEN_RUN_FLUSHELEVEN_RUN_FLUSHTWELVE_RUN_FLUSHTHIRTEEN_RUN_FLUSH"

var _Format_index = [...]uint16{0, 5, 11, 15, 21, 25, 34, 42, 50, 57, 66, 75, 83, 90, 100, 110, 122, 137, 151, 165, 178, 193, 208, 222, 235, 251, 267, 285}

func (i Format) String() string {
	if i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
